// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH6B-jHGWb8U24HxBYPsQwMUTcxrrPok0',
    appId: '1:177126854421:web:983d03fa982e575f05631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    authDomain: 'flash-chat-flutter-19b81.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
    measurementId: 'G-W9S9RS435P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLIegSlSk-gXnM01ZYFDDd93KSsVJRgGI',
    appId: '1:177126854421:android:9f0c938a33bcea2b05631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZxOoIWBJR1yCkKlm3eLyfb720OBFfRFs',
    appId: '1:177126854421:ios:be6e29860e3358ad05631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
    iosClientId: '177126854421-on0phn91o88e6m5japea1l148997uv6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZxOoIWBJR1yCkKlm3eLyfb720OBFfRFs',
    appId: '1:177126854421:ios:be6e29860e3358ad05631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
    iosClientId: '177126854421-on0phn91o88e6m5japea1l148997uv6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH6B-jHGWb8U24HxBYPsQwMUTcxrrPok0',
    appId: '1:177126854421:web:ad8c77dec1a5374f05631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    authDomain: 'flash-chat-flutter-19b81.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
    measurementId: 'G-LP8DBH7839',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBH6B-jHGWb8U24HxBYPsQwMUTcxrrPok0',
    appId: '1:177126854421:web:713bc9b7d0be811105631c',
    messagingSenderId: '177126854421',
    projectId: 'flash-chat-flutter-19b81',
    authDomain: 'flash-chat-flutter-19b81.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-19b81.appspot.com',
    measurementId: 'G-VHFLMJ3D41',
  );
}
